In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import geopandas as gpd

In [2]:
import folium
from ipywidgets.embed import embed_minimal_html
from IPython.display import display, HTML

In [3]:
plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['figure.figsize'] = (10,10)

## 지도 데이터

In [4]:
map_data = 'map/SIG/sig.shp'
map = gpd.read_file(map_data,encoding='euc-kr')
map.tail()

,SIG_CD,SIG_ENG_NM,SIG_KOR_NM,geometry
167,43111,Cheongju,청주,"POLYGON ((1010533.214 1856610.411, 1010536.149..."
168,47111,Pohang-si,포항,"MULTIPOLYGON (((1181905.008 1785427.049, 11819..."
169,48121,Changwon,창원,"MULTIPOLYGON (((1103125.017 1692322.123, 11031..."
170,44131,Cheonan,천안,"POLYGON ((981931.111 1876834.770, 981951.314 1..."
171,31110,Ulsan,울산,"MULTIPOLYGON (((1169009.652 1729037.319, 11689..."

In [5]:
mdf = map.reset_index().drop(columns=['index'])
mdf['location'] = mdf.SIG_KOR_NM

## 변수 데이터

In [6]:
data = pd.read_csv('data/unmatch_data.csv',encoding='cp949')
data.head()

,Unnamed: 0,location,year,month,lon,lat,height,avg_tem,precip,wind,min_tem,hPa,sun,g_tem,start,climax
0,0,속초,1989,1,128.5647,38.2509,17.53,1.5,165.9,2.8,-1.5,1023.7,111.6,0.8,286,297
1,1,속초,1989,2,128.5647,38.2509,17.53,2.7,65.3,2.6,-0.5,1022.4,154.2,1.9,286,297
2,2,속초,1989,3,128.5647,38.2509,17.53,5.9,121.7,3.2,2.6,1017.0,175.4,6.1,286,297
3,3,속초,1989,4,128.5647,38.2509,17.53,12.4,6.2,3.2,7.5,1013.3,228.1,14.2,286,297
4,4,속초,1989,5,128.5647,38.2509,17.53,16.5,66.8,3.5,12.5,1010.6,253.7,18.7,286,297

In [7]:
wdf = data.drop(columns=['Unnamed: 0'])
wdf.tail()

,location,year,month,lon,lat,height,avg_tem,precip,wind,min_tem,hPa,sun,g_tem,start,climax
19131,남해,2007,8,127.9264,34.8166,45.71,26.6,290.5,1.5,23.7,1004.3,172.7,28.3,311,319
19132,남해,2007,9,127.9264,34.8166,45.71,22.0,429.0,1.5,19.2,1006.7,118.4,23.3,311,319
19133,남해,2007,10,127.9264,34.8166,45.71,16.9,132.5,1.4,13.1,1013.4,208.2,18.4,311,319
19134,남해,2007,11,127.9264,34.8166,45.71,9.4,0.0,1.6,4.4,1017.1,204.4,10.0,311,319
19135,남해,2007,12,127.9264,34.8166,45.71,5.1,58.0,1.9,1.4,1015.9,159.0,4.5,311,319

## 지도데이터, 변수데이터 결합

In [8]:
test = pd.merge(mdf,wdf, how='outer',on='location')

In [9]:
cond = (test.geometry != None)

convert = test[cond]

In [16]:
sig_autumn = gpd.GeoDataFrame(convert,geometry=convert.geometry)
sig_autumn.set_crs = {'init':'epsg:5179'}

## shp 파일로 저장

In [17]:
sig_autumn.to_file('map/match_data/sig_autumn.shp', driver='ESRI Shapefile', encoding='cp949')

KeyboardInterrupt: